name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Instal wasm-pack
      run: cargo install wasm-pack
    - name: Build Rust
      run: wasm-pack build
    - name: Build website
      run: cd www; npm install; npm run build
    
